---
name: Deploy a new S3 bucket with S3 Event Notifications configured.
on:
  # Specify this workflow as Manually triggered
  workflow_dispatch:
    inputs:
      # Used to set the S3 bucket name in the create-bucket script
      bucket_name:
        description: 'New S3 bucket name (MUST be globally unique!)'
        default: 'new_bucket'
        required: true
      # Used to set the SNS notification email address in the create-email-lambda script
      email_address:
        description: 'Email Address for SNS notifications'
        default: 'foo@bar.com'
        required: true
jobs:
  create-and-deploy-new-bucket-to-aws:
    name: 'Create and Deploy new S3 bucket to AWS'
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      id-token: 'write'
    env:
      GITHUB_USERNAME: NicholasYamamoto

    steps:
      - name: 'Configuring S3 Event Notification email address.'
        run: echo "S3 Event Notifications will be sent via SNS to ${{ github.event.inputs.email_address }}"

      - name: 'Checking out the latest Master branch.'
        uses: actions/checkout@v3

      - name: 'Installing and configuring the `setup-terraform` GitHubActions library.'
        uses: hashicorp/setup-terraform@v2

      - name: 'Formatting Terraform code before initialization'
        id: 'fmt'
        run: terraform fmt -check

      - name: 'Initializing the Terraform project'
        id: 'init'
        run: terraform init

      - name: 'Validating the Terraform projects initialization'
        id: 'validate'
        run: terraform validate -no-color

      - name: 'Running `terraform plan'
        id: 'plan'
        run: |-
          terraform plan -var="bucket_name=${{ github.event.inputs.bucket_name }}" -var="sns_email_address=${{ github.event.inputs.email_address }}" -no-color -input=false

      - name: 'Running `terraform apply` with the workflow inputs'
        id: 'apply'
        run: |-
          terraform apply -var="bucket_name=${{ github.event.inputs.bucket_name }}" -var="sns_email_address=${{ github.event.inputs.email_address }}" -no-color -input=false


